version: '3.9'
services:

  dashboard:
    image: abhinav1002/api-gateway-dashboard:latest
    ports:
      - "5173:5173"
    depends_on:
      - gateway

  gateway:
    image: abhinav1002/api-gateway:latest
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    depends_on:
      - user
      - product
      - order
      - redis

  user:
    image: abhinav1002/api-gateway-user:latest
    ports:
      - "4001:4001"

  product:
    image: abhinav1002/api-gateway-product:latest
    ports:
      - "4002:4002"

  order:
    image: abhinav1002/api-gateway-order:latest
    ports:
      - "4003:4003"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"